# Generated by Django 3.2.7 on 2021-09-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
